version: '2'

services:
  gocloud:
    build: ./
    ports:
      - "8080:8080"
    command: npm run start:dev
    env_file:
      - ./.env
    depends_on:
      - mongodb-gocloud
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb-gocloud:
    image: docker.io/bitnami/mongodb:5.0
    ports:
      - "27018:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local